name: Personal professional website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - uses: actions/checkout@v6.0.1

      - name: install node modules
        run: npm install

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_VITE_API_URL: "http://ps-api.daveywalbeck.com"
          envkey_VITE_GITHUB_URL: "https://github.com/dwalbeck/"
          envkey_VITE_LINKEDIN_URL: "https://www.linkedin.com/in/daveywalbeck/"
          envkey_VITE_CONTACT_EMAIL: "daveywalbeck@gmail.com"
          envkey_VITE_FILES_RESUME: "./resume-davey_walbeck.docx"
          file_name: .env

      - name: compile the code
        run: npm run build

      - name: copy files to web server
        uses: appleboy/scp-action@v1
        with:
          host: 54.237.75.43
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: ./dist/*
          target: /var/www/personal_site/

