name: Personal professional website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - uses: actions/checkout@v6.0.1

      - name: install node modules
        run: npm install

      - name: Make envfile
        uses: aasmal97/create-env-file@v3.1.2
        with:
          APP_SECRETS: ${{toJson(secrets)}}
          ENV_FILE_NAME: ".env"
          DESTINATION_PATH: ${{ github.workspace }}/src

      - name: compile the code
        run: npm run build

      - name: copy files to web server
        run: |
          echo '$SSH_KEY' > key.pem
          scp -r -i key.pem $SRC $USER@$RHOST:$DEST
        env:
          SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          RHOST: 54.237.75.43
          USER: deploy
          SRC: './dist/*'
          DEST: '/var/www/personal_site/'

#        uses: i3h/deploy-with-scp@v1
#        with:
#          server-ip: 54.237.75.43
#          username: deploy
#          ssh-key: ${{secrets.SSH_PRIVATE_KEY}}
        #  port: 22
#          src: './dist/*'
#          dest: '/var/www/personal_site/'


