name: Personal professional website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - uses: actions/checkout@v6.0.1

      - name: install node modules
        run: npm install

      - name: Make envfile
        uses: aasmal97/create-env-file@v3.1.2
        with:
          APP_SECRETS: ${{toJson(secrets)}}
          ENV_FILE_NAME: ".env"
          DESTINATION_PATH: ${{ github.workspace }}/src

      - name: compile the code
        run: npm run build

      - name: write ssh key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/pri-key.pem
          chmod 600 ~/.ssh/pri-key.pem

      - name: copy files to web server
        uses: reene444/scp-transfer-action@v1.0.0
        with:
          remote_host: "54.237.75.43"
          remote_user: "deploy"
          ssh-key-path: "~/.ssh/pri-key.pem"
#          key: ${{secrets.SSH_PRIVATE_KEY}}
#          port: "22"
#          source: "./dist/*"
          remote_path: "/var/www/personal_site/"


